#!/bin/bash

if [ $# -ne 2 ];
    then
    echo "Usage: ./gpu-ssh.sh mattbraly 192.168.1.200"
elif [ $1 == -h ];
    then
    echo "Usage: ./gpu-ssh.sh mattbraly 192.168.1.200"
else
    ssh -L 8000:localhost:8888 $1"@"$2
fi

#ssh -L 8000:localhost:8888 your_name@your_server_ip
